on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: afrinic-dbwg/document-qa/document-qa
          tag_with_ref: true

