on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  image-build:
    runs-on: ubuntu-latest
    name: Image Build
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          repository: afrinic-dbwg/document-qa
          tag_with_ref: true

